### PR TITLE
fix: Add More Info on Equality Operators page

### PR DESCRIPTION
**Pull request by custardcream98**
# Issue

Resolves: #676

# Summery

`@debug 1 != 1px;` is `false`, and `@debug 1 != 1rem;` is also `false`.

So I've added some and fixed comment.

### CODE REVIEW

**Comment by custardcream98** [comment]
I've found out that it wasn't a typo, so I've added some more for those who get confused like me. 😂😂

**Comment by custardcream98** [comment]
So,

```scss
@debug 1 != 1px;
```

is `false` on LibSass version under 3.6.5
and `true` on LibSass version 3.6.5 thanks to [this change](https://github.com/sass/libsass/pull/3095)
(and also `true` on lateset Dart Sass)

**Comment by nex3** [comment]
Thanks for the contribution, but we've already got info about the change in equality behavior on that page, in our standardized component for describing cross-version/-implementation differences:

https://github.com/sass/sass-site/blob/02771170cf46382d33d0e5ca558135ea0d81ffbe/source/documentation/operators/equality.html.md.erb#L5-L11

**Comment by custardcream98** [comment]
Oh, I didn't notice that toggle button. Thanks! 👍

**Pull request closed without merging**
