### PR TITLE
Rewrite the contribution section.

### PR DESCRIPTION
**Pull request by nex3**
The high-level goal of this rewrite is to make it easier to contribute.
It focuses less on requirements, especially for tweaks that can easily
be added by Chris and I after the fact, and more on familiarizing
potential contributors with what to do and how to get help with it.

### CODE REVIEW

**Comment by nex3** [comment]
@jina What do you think about surfacing this more prominently in the site somehow? I want to start working harder on soliciting external contributions, and this is an important part of that.

**Comment by jina** [comment]
Sure, I'll take a look.

**Comment by nex3** [comment]
@jina Any update on this? I'd like to get it in on the sooner end, so I can put up a blog post pointing to it.

**Comment by jina** [comment]
Hey Natalie — I hadn’t had a chance yet. Been a little busy with Dreamforce coming up but will get to this as soon as I can. :) I think I can work on it next weekend. Sorry about the delay!

**Comment by nex3** [comment]
@jina Another friendly ping!

**Comment by jina** [comment]
@nex3 sorry I took so long to merge this.

Now that we have a "Adding Syntax" section, as well as an "Implementation Guide", I definitely think the Community section needs a major overhaul. It's been on my list for a while. I'll try my best to get to it once I can!

**Pull request merged**
