### PR TITLE
Add an Implementation Guide.

### PR DESCRIPTION
**Pull request by nex3**
This is designed to help creators of new Sass implementations know where
to start and what to avoid.

### CODE REVIEW

**Comment by nex3** [comment]
@chriseppstein @hcatlin Can you look over this and let me know what you think?

@jina Can you make it look not bad and also find a good place to link to it from the main site?

**Comment by jina** [comment]
Sure! I'll take a look over the weekend.

**Comment by chriseppstein** [comment]
:+1: This is a good first step. We can iterate on it as we learn.

**Comment by jina** [comment]
are you planning to expand it to subpages? noticed you used `implementation/index.html.haml` instead of `implementation.html.haml`. Not a big deal, but usually we keep things flat. :)

**Comment by jina** [comment]
I added three columns and moved to a flat file. Take a look. If you like what you see go ahead and merge.

**Comment by jina** [comment]
screenshot 2015-06-03 14 08 47
screenshot…

**Comment by nex3** [comment]
Looks awesome! The only thing left is to find somewhere to link to it from the rest of the site.

**Comment by jina** [comment]
Added a link on the community page. gonna merge

**Comment by jina** [comment]
Can one of you deploy? I still have problems with it

**Comment by nex3** [comment]
On it.

**Pull request merged**
