### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by mikaspell**
bundle update, as the eventmachine version 1.0.3 is not installing

fixed sitemap bug

### CODE REVIEW

**Comment by jina** [comment]
I think you have to update the Gemfile, not the Gemfile.lock, correct?

**Comment by mikaspell** [comment]
is not correct, it is a change in gemfile.lock enables successfully run bundle install

**Comment by jina** [comment]
but gemfile is the working file. gemfile.lock is generated from gemfile. gemfile.lock is not supposed to be manually edited as far as I know?


—

**Comment by mikaspell** [comment]
yes you are right, if you run 'bundle update' then gemfile.lock will be overwritten automatically , and it just keeps the necessary versions of gems. But when running the command 'bundle install' is being held gemfile.lock and installs the required version of the gems. Thus, I want to say that you can manually change the file if you know exactly what version of gem you need. Let me make another pull request after executing the command 'bundle update' as there are not only upgraded eventmachine

**Comment by mikaspell** [comment]
updated pull

**Pull request closed without merging**
