### PR TITLE
Build JS API docs from the TypeScript declarations

### PR DESCRIPTION
**Pull request by nex3**

### CODE REVIEW

**Comment by nex3** [comment]
I'll put up a preview once https://github.com/sass/sass/pull/3174 lands.

**Comment by nex3** [comment]
All right, preview is up at https://staging-sass-lang.herokuapp.com/documentation/js-api. @jina feel free to take a design pass too if you've got time/desire.

**Comment by jathak** [comment]
It looks like the links on the main page under "Usage" are broken. `LegacyFileOptions` and `LegacyStringOptions` are 404s and the other links link to the built-in modules doc.

**Comment by nex3** [comment]
> It looks like the links on the main page under "Usage" are broken. `LegacyFileOptions` and `LegacyStringOptions` are 404s and the other links link to the built-in modules doc.

Good eye! I wonder why the automated link checker isn't flagging these...

**Comment by nex3** [comment]
Oh I think I understand why: the link checker sees the URL as `/documentation/js-api/index.html`, so it's able to resolve relative URLs that wouldn't resolve from `/documentation/js-api`. Gross.

**Comment by nex3** [comment]
Those links should be working now: https://staging-sass-lang.herokuapp.com/documentation/js-api

**Review by jathak — APPROVED** [review]

**Pull request merged**
