### PR TITLE
new grid system flexible.gs sass

### PR DESCRIPTION
**Pull request by dnomak**

### CODE REVIEW

**Comment by dnomak** [comment]
@jina when will the publication?

**Comment by dnomak** [comment]
@jina ?

**Comment by jina** [comment]
Next time the site gets deployed it will be up. I can't on my laptop I'm using right now.  As soon as I get a chance to on my other computer I can. Please be patient. :) Unless someone else with access has the chance? :) @chriseppstein?

—

**Comment by dnomak** [comment]
thanks @jina :) @chriseppstein

**Pull request merged**
