### PR TITLE
fix(docs): correct default import example about default export

### PR DESCRIPTION
**Pull request by nazarepiedady**
I am applying a subtle typo correction to the `breaking-changes/default-export.md` document in this pull request.
I found this typo while translating this document for the translated version of the website I am working on.

@nex3

### CODE REVIEW

**Comment by nazarepiedady** [comment]
@nex3 is this issue already fixed?
Because I could close this pull request if so.

**Comment by nex3** [comment]
I don't think this is fixed, but it does look like you need to rebase this onto the latest main branch.

**Comment by nazarepiedady** [comment]
@nex3 the pull request is updated, I believe that now is possible to go ahead to the next stage.

**Comment by nex3** [comment]
This still isn't rebased against the latest HEAD (you can tell because it has a bunch of duplicate commits listed, instead of just one small commit).

**Comment by nazarepiedady** [comment]
@nex3 I have no idea, and I cannot see a conflict until now. If it is not possible to do the merge, could you use the `cherry-pick` to only add to the main change I have made?

**Review by Goodwine — APPROVED** [review]

**Pull request merged**
