### PR TITLE
Update the documentation to cover Dart Sass

### PR DESCRIPTION
**Pull request by nex3**
**Please don't merge this until Dart Sass 1.0.0 is released.**

@jina I tried to follow the existing design of the site, but I'm not a
designer so please tweak as necessary. I'm especially unsure if the
CSS changes are right.

### CODE REVIEW

**Comment by jina** [comment]
I'll take a look when I get back to SF (I fly back from Finland soon).

**Comment by nex3** [comment]
@jina Do you have a sense of when you'll be able to look at this? I'd like to launch next week if possible.

**Comment by nex3** [comment]
Also, thanks to :sparkles:fancy heroku magic:sparkles: you can view [a deployed copy of this app](https://sass-lang-pr-208.herokuapp.com/)! Unfortunately the fonts don't work right, though, since Typekit is only configured for sass-lang.com.

**Comment by jina** [comment]
ooooh deploy apps. that's so fun! I think this looks good enough to merge. i noticed a few things I'd like to tweak but I can do that later. I was planning to do a slight update soon anyway. (for example, bumping color contrast, cleaning up the layouts, etc). will do once things kinda calm down on my end. :)

**Pull request merged**
